// <auto-generated />
using System;
using APBD_TEST_LastTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_TEST_LastTest.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250609104217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RaceId");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Some location",
                            Name = "Some Race"
                        },
                        new
                        {
                            RaceId = 2,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Another location",
                            Name = "Another Race"
                        },
                        new
                        {
                            RaceId = 3,
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Yet another location",
                            Name = "Yet another Race"
                        });
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.RaceParticipation", b =>
                {
                    b.Property<int>("RacerId")
                        .HasColumnType("int");

                    b.Property<int>("TrackRaceId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("RacerId", "TrackRaceId");

                    b.HasIndex("TrackRaceId");

                    b.ToTable("Race_Participation");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            TrackRaceId = 1,
                            FinishTimeInSeconds = 10,
                            Position = 1
                        },
                        new
                        {
                            RacerId = 2,
                            TrackRaceId = 2,
                            FinishTimeInSeconds = 19,
                            Position = 1
                        },
                        new
                        {
                            RacerId = 3,
                            TrackRaceId = 3,
                            FinishTimeInSeconds = 29,
                            Position = 1
                        },
                        new
                        {
                            RacerId = 1,
                            TrackRaceId = 4,
                            FinishTimeInSeconds = 30,
                            Position = 1
                        });
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Racer", b =>
                {
                    b.Property<int>("RacerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RacerId");

                    b.ToTable("Racer");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            FirstName = "Gleb",
                            LastName = "Denisov"
                        },
                        new
                        {
                            RacerId = 2,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            RacerId = 3,
                            FirstName = "Janette",
                            LastName = "Doj"
                        });
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<double>("LengthInKM")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrackId");

                    b.ToTable("Track");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            LengthInKM = 10.02,
                            Name = "1 Track"
                        },
                        new
                        {
                            TrackId = 2,
                            LengthInKM = 20.09,
                            Name = "2 Track"
                        },
                        new
                        {
                            TrackId = 3,
                            LengthInKM = 30.120000000000001,
                            Name = "3 Track"
                        },
                        new
                        {
                            TrackId = 4,
                            LengthInKM = 40.119999999999997,
                            Name = "4 Track"
                        });
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.TrackRace", b =>
                {
                    b.Property<int>("TrackRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackRaceId"));

                    b.Property<int?>("BestTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("TrackRaceId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TrackId");

                    b.ToTable("Track_Race");

                    b.HasData(
                        new
                        {
                            TrackRaceId = 1,
                            Laps = 10,
                            RaceId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            TrackRaceId = 2,
                            BestTimeInSeconds = 29,
                            Laps = 20,
                            RaceId = 2,
                            TrackId = 2
                        },
                        new
                        {
                            TrackRaceId = 3,
                            Laps = 10,
                            RaceId = 3,
                            TrackId = 3
                        },
                        new
                        {
                            TrackRaceId = 4,
                            BestTimeInSeconds = 10,
                            Laps = 10,
                            RaceId = 2,
                            TrackId = 2
                        });
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.RaceParticipation", b =>
                {
                    b.HasOne("APBD_TEST_LastTest.Models.Racer", "Racer")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("RacerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_TEST_LastTest.Models.TrackRace", "TrackRace")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("TrackRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racer");

                    b.Navigation("TrackRace");
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.TrackRace", b =>
                {
                    b.HasOne("APBD_TEST_LastTest.Models.Race", "Race")
                        .WithMany("TrackRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_TEST_LastTest.Models.Track", "Track")
                        .WithMany("TrackRaces")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Race", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Racer", b =>
                {
                    b.Navigation("RaceParticipations");
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.Track", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("APBD_TEST_LastTest.Models.TrackRace", b =>
                {
                    b.Navigation("RaceParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
